Informacni_System_Pojistovny/Controllers/HistorieController.cs
using Informacni_System_Pojistovny.Models.Dao;
using Informacni_System_Pojistovny.Models.Entity;
using Informacni_System_Pojistovny.Models.Model.UzivatelHistorie;
using Informacni_System_Pojistovny.Models.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Informacni_System_Pojistovny.Models.Model.Historie;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Informacni_System_Pojistovny.Controllers
{
    public class HistorieController : Controller
    {
        private readonly Db _db;
        public HistorieController(Db db)
        {
            _db = db;
        }
        // GET: Historie
        [Authorize(Roles = nameof(UzivateleRole.Admin))]
        public ActionResult Index(PageInfo pageInfo)
        {
            HistorieModel historieModel = new HistorieModel(_db);
            List<Historie> historie = historieModel.ListHistorie(pageInfo);
            long count = historieModel.GetCount();
            ViewBag.count = count;

            ViewBag.PageSize = pageInfo.PageSize;
            ViewBag.PageIndex = pageInfo.PageIndex;
            _db.Dispose();
            return View(historie);
        }
    }
}

Informacni_System_Pojistovny/Controllers/KlientController.cs
using Informacni_System_Pojistovny.Models.Dao;
using Informacni_System_Pojistovny.Models.Entity;
using Informacni_System_Pojistovny.Models.Model;
using Informacni_System_Pojistovny.Models.Model.DokumentModels;
using Informacni_System_Pojistovny.Models.Model.PohledavkaModels;
using Informacni_System_Pojistovny.Models.Model.Pojistka;
using Informacni_System_Pojistovny.Models.Model.PojistnyProduktModels;
using Informacni_System_Pojistovny.Models.Model.ZavazekModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Text;

namespace Informacni_System_Pojistovny.Controllers
{
    public class KlientController : Controller
    {
        private readonly Db _db;

        public KlientController(Db db)
        {
            _db = db;
        }


        // GET: KlientController
        [Authorize(Roles = $"{nameof(UzivateleRole.User)},{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)} ")]
        public ActionResult Index(PageInfo pageInfo, string CurrentFilter)
        {
            KlientModel klientModel = new KlientModel(_db);

            long count = klientModel.GetCount(CurrentFilter);
            ViewBag.count = count;
            ViewBag.CurrentFilter = CurrentFilter;

            ViewBag.PageSize = pageInfo.PageSize;
            ViewBag.PageIndex = pageInfo.PageIndex;
            List<Klient> klients = klientModel.ReadClients(pageInfo, CurrentFilter);
            _db.Dispose();
            return View(klients);
        }

        // GET: KlientController/Details/5
        [Authorize(Roles = $"{nameof(UzivateleRole.User)},{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Details(int id)
        {
            Klient klient = new();
            try
            {
                KlientModel klientDb = new KlientModel(_db);
                PohledavkaModel pohledavkaModel = new PohledavkaModel(_db);
                ZavazekModel zavazekModel = new ZavazekModel(_db);
                klient = klientDb.GetClient(id);
                klient.Adresy = klientDb.GetClientAddresses(id);
                klient.Dokumenty = klientDb.ReadClientDocuments(id);
                //pro pohledavky
                klient.Pojistky?.ForEach(pojistka =>
                    pojistka.Pohledavky = pohledavkaModel.ListPohledavka(pojistka.ID)
                );
                klient.PojistneUdalosti?.ForEach(pojistnaUdalost =>
                    pojistnaUdalost.Zavazky = zavazekModel.ListZavazek(pojistnaUdalost.PojistnaUdalostId)
                );
            }
            catch (Exception ex)
            {
                ViewBag.errorMessage = ex.Message;
            }
            _db.Dispose();
            return View(klient);
        }

        // GET: KlientController/Create
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create()
        {
            PscModel pscModel = new PscModel(_db);
            List<SelectListItem> pscs = pscModel.ReadPscsAsSelectListItems();
            ViewBag.pscs = pscs;
            _db.Dispose();
            return View();
        }

        // GET: KlientController/AddAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult AddAddress(int id)
        {
            PscModel pscModel = new PscModel(_db);
            List<SelectListItem> pscs = pscModel.ReadPscsAsSelectListItems();
            ViewBag.pscs = pscs;
            _db.Dispose();
            return View();
        }

        // POST: KlientController/AddAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        [HttpPost]
        public ActionResult AddAddress(AdresaInputModel adresa, int id)
        {
            if (ModelState.IsValid)
            {
                KlientModel klientModel = new KlientModel(_db);
                try
                {
                    klientModel.AddAddressToClient(id, adresa);
                }
                catch (Exception ex)
                {
                    ViewBag.errorMessage = ex.Message;
                }

                _db.Dispose();
                return RedirectToAction(nameof(Details), new { id });
            }
            else return View();
        }

        // GET: KlientController/EditAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult EditAddress(int id, int redirectTo)
        {
            AdresaInputModel adresaInputModel = new();
            try
            {
                PscModel pscModel = new PscModel(_db);
                List<SelectListItem> pscs = pscModel.ReadPscsAsSelectListItems();
                AdresaModel adresaModel = new AdresaModel(_db);
                adresaInputModel = adresaModel.ReadAddressAsEditModel(id);
                ViewBag.redirectTo = redirectTo;
                ViewBag.pscs = pscs;
            }
            catch (Exception ex)
            {
                _db.Dispose();
                ViewBag.errorMessage = ex.Message;
            }
            _db.Dispose();
            return View(adresaInputModel);
        }

        // ´POST: KlientController/AddAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        [HttpPost]
        public ActionResult EditAddress(AdresaInputModel adresa, int id, IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var x = RouteData.Values["redirectTo"];
                AdresaModel adresaModel = new AdresaModel(_db);
                adresaModel.EditAddress(id, adresa);
                _db.Dispose();
                return RedirectToAction(nameof(Details), new { id = collection["redirectTo"] });
            }
            else return View();
        }

        // GET: KlientController/DeleteAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult DeleteAddress(int id, int redirectTo)
        {
            PscModel pscModel = new PscModel(_db);
            List<SelectListItem> pscs = pscModel.ReadPscsAsSelectListItems();
            AdresaModel adresaModel = new AdresaModel(_db);
            AdresaInputModel adresaInputModel = adresaModel.ReadAddressAsEditModel(id);
            ViewBag.pscs = pscs;
            ViewBag.redirectTo = redirectTo;
            _db.Dispose();
            return View(adresaInputModel);
        }

        // ´POST: KlientController/AddAddress
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        [HttpPost]
        public ActionResult DeleteAddress(AdresaInputModel adresa, int id, IFormCollection collection)
        {
            AdresaModel adresaModel = new AdresaModel(_db);
            adresaModel.DeleteAddress(id);
            _db.Dispose();
            return RedirectToAction(nameof(Details), new { id = collection["redirectTo"] });
        }

        // POST: KlientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create(KlientCreateModel model, IFormCollection collection)
        {
            if (collection["zvolenyTypOsoby"].Equals("F"))
            {
                ModelState.Remove("Ico");
                ModelState.Remove("Nazev");
            }
            else
            {
                ModelState.Remove("Jmeno");
                ModelState.Remove("Prijmeni");
                ModelState.Remove("Telefon");
                ModelState.Remove("RodneCislo");
                ModelState.Remove("Email");
            }
            if (ModelState.IsValid)
            {
                KlientModel klientDb = new KlientModel(_db);
                klientDb.CreateClient(collection);
                _db.Dispose();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        // GET: KlientController/Edit/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Edit(int id)
        {
            KlientModel klientDb = new KlientModel(_db);
            KlientEditModel klient = klientDb.GetEditClient(id);
            if (klient == null)
            {
                ViewBag.errorMessage = "Klient nebyl nalezen";
                _db.Dispose();
                return RedirectToAction(nameof(Details), new { id });
            }
            else
            {
                _db.Dispose();
                return View(klient);
            }
        }

        // POST: KlientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Edit(int id, KlientEditModel model, IFormCollection collection)
        {
            if (collection["zvolenyTypOsoby"].Equals("F"))
            {
                ModelState.Remove("Ico");
                ModelState.Remove("Nazev");
            }
            else
            {
                ModelState.Remove("Jmeno");
                ModelState.Remove("Prijmeni");
                ModelState.Remove("Telefon");
                ModelState.Remove("RodneCislo");
                ModelState.Remove("Email");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    KlientModel klientDb = new KlientModel(_db);

Informacni_System_Pojistovny/Controllers/PscController.cs
using Informacni_System_Pojistovny.Models.Dao;
using Informacni_System_Pojistovny.Models.Entity;
using Informacni_System_Pojistovny.Models.Model;
using Informacni_System_Pojistovny.Models.Model.PojistnyProduktModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Informacni_System_Pojistovny.Controllers
{
    public class PscController : Controller
    {
        private readonly Db _db;

        public PscController(Db db)
        {
            _db = db;
        }

        // GET: PscController
        [Authorize(Roles = $"{nameof(UzivateleRole.User)},{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Index(PageInfo pageInfo, string CurrentFilter)
        {
            PscModel pscModel = new PscModel(_db);

            long count = pscModel.GetCount(CurrentFilter);
            ViewBag.count = count;

            ViewBag.PageSize = pageInfo.PageSize;
            ViewBag.PageIndex = pageInfo.PageIndex;
            ViewBag.CurrentFilter = CurrentFilter;
            _db.Dispose();

            return View(pscModel.ReadPscs(pageInfo, CurrentFilter));
        }

        // GET: PscController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create(Psc psc)
        {
            if (ModelState.IsValid)
            {
                PscModel pscModel = new PscModel(_db);
                pscModel.CreatePsc(psc);
                _db.Dispose();
                return RedirectToAction(nameof(Index));
            }
            else { 
                return View();
            }
        }

        // GET: KlientController/Create
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create()
        {
            return View();
        }

        // GET: PscController/Edit/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Edit(string id)
        {
            PscModel pscModel = new PscModel(_db);
            PscEditModel psc = pscModel.ReadPscAsEditModel(id);
            _db.Dispose();
            return View(psc);
        }

        // POST: PscController/Edit/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, PscEditModel pscEditModel)
        {
            if (ModelState.IsValid)
            {
                PscModel pscModel = new PscModel(_db);
                if (pscModel.EditPsc(id, pscEditModel)) {
                    _db.Dispose();
                    return RedirectToAction(nameof(Index));
                } else return View();
            } else return View();
        }

        // GET: PscController/Delete/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Delete(string id)
        {
            PscModel pscModel = new PscModel(_db);
            Psc psc = pscModel.ReadPsc(id);
            _db.Dispose();
            if (psc == null) {
                ViewBag.errorMessage = "Psč nebylo nalezeno";
            }
            return View(psc);
        }

        // POST: PscController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Delete(string id, Psc psc)
        {
            try
            {
                PscModel pscModel = new PscModel(_db);
                pscModel.DeletePSC(id);
                _db.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.errorMessage = ex.Message;
                PscModel pscModel = new PscModel(_db);
                psc = pscModel.ReadPsc(id);
                _db.Dispose();
                return View(psc);
            }
        }
    }
}

Informacni_System_Pojistovny/Controllers/UserObjectsController.cs
using Informacni_System_Pojistovny.Models.Dao;
using Informacni_System_Pojistovny.Models.Entity;
using Informacni_System_Pojistovny.Models.Model.UserObjectsModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Informacni_System_Pojistovny.Controllers
{
    public class UserObjectsController : Controller
    {
        private readonly Db _db;

        public UserObjectsController(Db db)
        {
            _db = db;
        }
        // GET: UserObjects
        [Authorize(Roles = nameof(UzivateleRole.Admin))]
        public ActionResult Index()
        {
            UserObjectsModel userObjectsModel = new UserObjectsModel(_db);
            List<UserObjects> userObjects = userObjectsModel.ReadUserObjects();
            _db.Dispose();
            return View(userObjects);
        }
    }
}

Informacni_System_Pojistovny/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Informační systém pojišťovny</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Informacni_System_Pojistovny.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div>
            @if (Context.User.Identity.IsAuthenticated)
            {
                Claim claim = Context.User.Claims.Where((claim) => claim.Type == "originalMail").FirstOrDefault();
                if (claim != null)
                {
                    <div  class="impersonification">
                                         <span>Impersonifikace je aktivní. Originální účet: <b>@claim.Value</b> <a asp-controller="Uzivatel" asp-action="ZrusImpersonifikaci">Zrušit&nbspimpersonifikaci</a></span>
                    </div>               
                }
            }
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid text-light">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Informační systém pojišťovny</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Domů</a>
                        </li>
                        @if (Context.User.IsInRole(UzivateleRole.User.ToString()) || Context.User.IsInRole(UzivateleRole.Admin.ToString()) || Context.User.IsInRole(UzivateleRole.PriviledgedUser.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Klient" asp-action="Index">Klienti</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Psc" asp-action="Index">PSČ</a>
                            </li>
                           <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="PojistnaUdalost" asp-action="Index">Pojistné události</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Zavazek" asp-action="Index">Závazky</a>
                           </li>
                            <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Pohledavka" asp-action="Index">Pohledávky</a>
                               </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Pobocka" asp-action="Index">Pobočky</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="PojistnyProdukt" asp-action="Index">Pojistné produkty</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Pojistka" asp-action="Index">Sjednané pojistky</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Podminka" asp-action="Index">Podmínky</a>
                            </li>
                        }
                        @if (Context.User.IsInRole(UzivateleRole.Admin.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Uzivatel" asp-action="Index">Uživatelé</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="UzivatelHistorie" asp-action="Index">Historie uživatelů</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Historie" asp-action="Index">Historie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="UserObjects" asp-action="Index">User objects</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
            <div class="emptyLoginWrapper">
                <div class="loginWindow collapse">
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (@ViewBag.errorMessage != null)
            {
                <div class="errorDiv" id="errorModal">
                    <div class="closeModal">
                            <div id="closeX">X</div>
                    </div>
                    <h5>Došlo k aplikační chybě</h5>
                    @ViewBag.errorMessage
                </div>
                <script>
                        let errorModal = document.querySelector("#errorModal")
                            let close = document.querySelector("#closeX")
                                    close.onclick = (event) =>{
                                        errorModal.style.display="none"
                            }
                </script>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Informační systém pojišťovny
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Informacni_System_Pojistovny/Views/Shared/_paging.cshtml
    <div>
    @{
        //show 10 pages
        string textFilter = ViewBag.CurrentFilter;
        long pageSize = ViewBag.PageSize;
        long pageIndex = ViewBag.PageIndex;
        long countMin1 = ViewBag.count - 1;
        long currentSelectedIndex = pageSize * pageIndex;
        //get min and max selectable item
        long startIndex = currentSelectedIndex - (5 * pageSize);
        if (currentSelectedIndex > countMin1)
        {
            startIndex = countMin1 - (9 * pageSize);
        }
        startIndex = startIndex < 0 ? 0 : startIndex;
        long endIndex = startIndex + 9 * pageSize;
        endIndex = endIndex > countMin1 ? countMin1 : endIndex;
        for (long i = startIndex / pageSize; i <= endIndex / pageSize; i++)
        {
            long pageNum = i + 1;
            if (i != pageIndex)
            {
                <a class="paging" asp-action="index" asp-route-pageInfo.pageSize=@pageSize asp-route-pageInfo.pageIndex =@i asp-route-CurrentFilter=@textFilter>@pageNum</a>
            }
            else
            {
                <a class="current paging" asp-action="index" asp-route-pageInfo.pageSize=@pageSize asp-route-pageInfo.pageIndex=@i asp-route-CurrentFilter=@textFilter>@pageNum</a>
            }
        }    
    }
    </div>