Informacni_System_Pojistovny/Models/Entity/Zavazek.cs
using System.ComponentModel.DataAnnotations;

namespace Informacni_System_Pojistovny.Models.Entity
{
    public class Zavazek
    {
        [Required]
        public int ZavazekId { get; set; }
        [Display(Name = "Vznik"), Required]
        [DataType(DataType.Date)]
        public DateTime Vznik { get; set; } = DateTime.Now;
        [Display(Name = "Datum splatnosti"), Required]
        [DataType(DataType.Date)]
        public DateTime DatumSplatnosti { get; set; } = DateTime.Now;
        [Display(Name = "Výše")]
        [DataType(DataType.Currency)]
        public int Vyse { get; set; }
        [Display(Name = "Datum splacení")]
        [DataType(DataType.Date)]
        public DateTime? DatumSplaceni { get; set; }
        [Display(Name = "Popis")]
        public string Popis { get; set; }
        [Display(Name = "Pojistná událost"), Required]
        public PojistnaUdalost PojistnaUdalost { get; set; }
    }
}

Informacni_System_Pojistovny/Controllers/PojistnaUdalostController.cs
using Informacni_System_Pojistovny.Models.Dao;
using Informacni_System_Pojistovny.Models.Entity;
using Informacni_System_Pojistovny.Models.Model;
using Informacni_System_Pojistovny.Models.Model.Pojistka;
using Informacni_System_Pojistovny.Models.Model.PojistnaUdalostModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System.Data;

namespace Informacni_System_Pojistovny.Controllers
{
    public class PojistnaUdalostController : Controller
    {
        private readonly Db _db;
        public PojistnaUdalostController(Db db)
        {
            _db = db;
        }
        // GET: PojistnaUdalostController
        [Authorize(Roles = $"{nameof(UzivateleRole.User)},{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Index(PageInfo pageInfo, string CurrentFilter)
        {
            PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
            List<PojistnaUdalost> pojistneUdalosti = pojistnaUdalostModel.ListPojistnaUdalost(pageInfo, CurrentFilter);

            long count = pojistnaUdalostModel.GetCount(CurrentFilter);
            ViewBag.count = count;
            ViewBag.CurrentFilter = CurrentFilter;

            ViewBag.PageSize = pageInfo.PageSize;
            ViewBag.PageIndex = pageInfo.PageIndex;
            _db.Dispose();
            return View(pojistneUdalosti);
        }

        // GET: PojistnaUdalostController/Details/5
        [Authorize(Roles = $"{nameof(UzivateleRole.User)},{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Details(int id, string exceptionMessage)
        {
            PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
            PojistnaUdalost pojistnaUdalost = pojistnaUdalostModel.GetPojistnaUdalost(id);
            if (pojistnaUdalost == null)
            {
                ViewBag.errorMessage = "Pojistná událost nebyla nalezena";

                //return RedirectToAction(nameof(Index));
            }
            else if(exceptionMessage != null)
            {
                ViewBag.errorMessage = exceptionMessage;
            }
            _db.Dispose();
            return View(pojistnaUdalost);
        }

        // GET: PojistnaUdalostController/Create
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create(int id = 0)
        {
            PojistnaUdalost pojistneUdalosti = new PojistnaUdalost();
            KlientModel klientModel = new KlientModel(_db);
            List<Klient> klients = klientModel.ReadClients();

            _db.Dispose();
            return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
        }

        // POST: PojistnaUdalostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Create(PojistnaUdalostCreateModel model)
        {
            ModelState.Remove("PojistnaUdalost.Klient");
            if (!ModelState.IsValid)
            {
                PojistnaUdalost pojistneUdalosti = new PojistnaUdalost();
                KlientModel klientModel = new KlientModel(_db);
                List<Klient> klients = klientModel.ReadClients();
                _db.Dispose();
                return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
            }
            try
            {
                KlientModel klientModel = new KlientModel(_db);
                Klient klient = klientModel.GetClient(model.KlientId);
                if (klient == null)
                {
                    ViewBag.errorMessage = "Zvolený klient nebyl nalezen";
                    return View();
                }
                PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
                pojistnaUdalostModel.CreatePojistnaUdalost(new PojistnaUdalost() { Klient = klient, NarokovanaVysePojistky = model.PojistnaUdalost.NarokovanaVysePojistky, Popis = model.PojistnaUdalost.Popis, Vznik = model.PojistnaUdalost.Vznik });
                _db.Dispose();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                PojistnaUdalost pojistneUdalosti = new PojistnaUdalost();
                KlientModel klientModel = new KlientModel(_db);
                List<Klient> klients = klientModel.ReadClients();
                ViewBag.errorMessage = ex.Message;
                _db.Dispose();
                return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
            }
        }

        // GET: PojistnaUdalostController/Edit/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Edit(int id)
        {
            PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
            PojistnaUdalost pojistnaUdalost = pojistnaUdalostModel.GetPojistnaUdalost(id);
            if (pojistnaUdalost == null)
            {
                ViewBag.errorMessage = "Pojistná událost nebyla nalezena";
            }
            KlientModel klientModel = new KlientModel(_db);
            List<Klient> klients = klientModel.ReadClients();
            _db.Dispose();
            return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistnaUdalost });
        }

        // POST: PojistnaUdalostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Edit(int id, PojistnaUdalostEditModel model)
        {
            string klientId = model.KlientId;
            if (!ModelState.IsValid)
            {
                PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
                PojistnaUdalost pojistneUdalosti = pojistnaUdalostModel.GetPojistnaUdalost(id);
                KlientModel klientModel = new KlientModel(_db);
                List<Klient> klients = klientModel.ReadClients();
                _db.Dispose();
                return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
            }
            try
            {
                KlientModel klientModel = new KlientModel(_db);
                Klient klient = klientModel.GetClient(int.Parse(klientId));
                _db.Dispose();
                if (klient == null)
                {
                    PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
                    PojistnaUdalost pojistneUdalosti = pojistnaUdalostModel.GetPojistnaUdalost(id);
                    List<Klient> klients = klientModel.ReadClients();
                    _db.Dispose();
                    return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
                }
                else
                {
                    PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
                    pojistnaUdalostModel.UpdatePojistnaUdalost(id, model);
                    _db.Dispose();
                    return RedirectToAction(nameof(Details), new { id });
                }
            }
            catch
            {
                PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
                PojistnaUdalost pojistneUdalosti = pojistnaUdalostModel.GetPojistnaUdalost(id);
                KlientModel klientModel = new KlientModel(_db);
                List<Klient> klients = klientModel.ReadClients();
                _db.Dispose();
                return View(new PojistnaUdalostCreateEditModel() { Klients = klients, PojistnaUdalost = pojistneUdalosti });
            }
        }

        // GET: PojistnaUdalostController/Delete/5
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Delete(int id)
        {
            PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
            PojistnaUdalost pojistnaUdalost = pojistnaUdalostModel.GetPojistnaUdalost(id);
            if (pojistnaUdalost == null)
            {
                ViewBag.errorMessage = "Pojistná událost nebyla nalezena";
                // return RedirectToAction(nameof(Index));
            }
            _db.Dispose();
            return View(pojistnaUdalost);
        }

        // POST: PojistnaUdalostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(UzivateleRole.PriviledgedUser)},{nameof(UzivateleRole.Admin)}")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            PojistnaUdalostModel pojistnaUdalostModel = new PojistnaUdalostModel(_db);
            try
            {
                pojistnaUdalostModel.DeletePojistnaUdalost(id);
                _db.Dispose();
                return RedirectToAction(nameof(Index), new { id });
            }
            catch (Exception ex)
            {
                _db.Dispose();
                ViewBag.errorMessage = ex.Message;
                return RedirectToAction(nameof(Details), new { id, exceptionMessage = ex.Message });
            }
        }
    }
}

Informacni_System_Pojistovny/Views/Zavazek/Create.cshtml
@model Informacni_System_Pojistovny.Models.Entity.Zavazek

@{
    ViewData["Title"] = "Vytvoření nového závazku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Vytvoření nového závazku</h1>

<h4>Závazek</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vznik" class="control-label"></label>
                <input asp-for="Vznik" class="form-control" />
                <span asp-validation-for="Vznik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumSplatnosti" class="control-label"></label>
                <input asp-for="DatumSplatnosti" class="form-control" />
                <span asp-validation-for="DatumSplatnosti" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vyse" class="control-label"></label>
                <input asp-for="Vyse" class="form-control" />
                <span asp-validation-for="Vyse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumSplaceni" class="control-label"></label>
                <input asp-for="DatumSplaceni" class="form-control" />
                <span asp-validation-for="DatumSplaceni" class="text-danger"></span>
            </div>
            <input hidden name="pojistnaUdalostId" value="@ViewBag.pojistnaUdalostId" />
            <div class="form-group">
                <label asp-for="Popis" class="control-label"></label>
                <input asp-for="Popis" class="form-control" />
                <span asp-validation-for="Popis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Vytvořit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="PojistnaUdalost" asp-route-id="@ViewBag.pojistnaUdalostId">Zpět na pojistnou událost</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Informacni_System_Pojistovny/Views/Zavazek/Delete.cshtml
@model Informacni_System_Pojistovny.Models.Model.ZavazekModels.RedirectableZavazekModel

@{
    ViewData["Title"] = "Smazání závazku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Smazání závazku</h1>

<h3>Opravdu chcete smazat tento závazek?</h3>
<div>
    <h4>Závazek</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vznik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vznik)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumSplatnosti)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumSplatnosti)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vyse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vyse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumSplaceni)
        </dt>
        <dd class = "col-sm-10">
            @{
                if (Model.DatumSplaceni != null)
                {
                //Html.DisplayFor(modelItem => item.DatumSplaceni);
                  <span>@(((DateTime)Model.DatumSplaceni).ToString("dd.MM.yyyy"))</span>
                }
                else
                {
                  <span>Nesplaceno</span>
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Popis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Popis)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input hidden asp-for="RedirectedFrom" class="form-control" />
        <input type="submit" value="Smazat" class="btn btn-danger" /> |
        @if (Model.RedirectedFrom == null)
        {
            <a asp-action="Index">Zpět na detail</a>
        }else{
            if (Model.RedirectedFrom.Equals("Klient"))
            {
                <a asp-action="Details" asp-controller="@Model.RedirectedFrom" asp-route-id=@Model.KlientId>Zpět na klienta</a>
            }
            else
            {
                <a asp-action="Details" asp-controller="@Model.RedirectedFrom" asp-route-id=@Model.PojistnaUdalostId>Zpět na pojistnou událost</a>
            }
        }
    </form>
</div>

Informacni_System_Pojistovny/Views/Zavazek/Details.cshtml
@model Informacni_System_Pojistovny.Models.Entity.Zavazek

@{
    ViewData["Title"] = "Detail závazku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>Závazek</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vznik)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vznik)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumSplatnosti)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DatumSplatnosti)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vyse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vyse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DatumSplaceni)
        </dt>
        <dd class = "col-sm-10">
            @{
                if (Model?.DatumSplaceni != null)
                {
                //Html.DisplayFor(modelItem => item.DatumSplaceni);
                                                                    <span>@(((DateTime)Model.DatumSplaceni).ToString("dd.MM.yyyy"))</span>
                }
                else
                {
                                          <span>Nesplaceno</span>
                }
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Popis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Popis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PojistnaUdalost)
        </dt>
        <dd class = "col-sm-10">
            @Html.ActionLink("Detail pojistné události", "Details","PojistnaUdalost", new { id=Model?.PojistnaUdalost?.PojistnaUdalostId })
        </dd>
    </dl>
</div>
<div>
            @if (Context.User.IsInRole(UzivateleRole.Admin.ToString()) || Context.User.IsInRole(UzivateleRole.PriviledgedUser.ToString()))
    {
       <span>@Html.ActionLink("Upravit", "Edit", new {  id = Model?.ZavazekId }) | </span>
    }
    <a asp-action="Index">Zpět na přehled</a>

    </div>

Informacni_System_Pojistovny/Views/Zavazek/Edit.cshtml
@model Informacni_System_Pojistovny.Models.Model.ZavazekModels.RedirectableZavazekModel

@{
    ViewData["Title"] = "Úprava závazku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Úprava závazku</h1>

<h4>Závazek</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vznik" class="control-label"></label>
                <input asp-for="Vznik" class="form-control" />
                <span asp-validation-for="Vznik" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumSplatnosti" class="control-label"></label>
                <input asp-for="DatumSplatnosti" class="form-control" />
                <span asp-validation-for="DatumSplatnosti" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vyse" class="control-label"></label>
                <input asp-for="Vyse" class="form-control" />
                <span asp-validation-for="Vyse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatumSplaceni" class="control-label"></label>
                <input asp-for="DatumSplaceni" class="form-control" />
                <span asp-validation-for="DatumSplaceni" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Popis" class="control-label"></label>
                <input asp-for="Popis" class="form-control" />
                <span asp-validation-for="Popis" class="text-danger"></span>
            </div>
               <input hidden asp-for="RedirectedFrom" class="form-control" />
               <input hidden asp-for="ZavazekId" class="form-control" />
               <input hidden asp-for="PojistnaUdalostId" class="form-control" />

            <div class="form-group">
                <input type="submit" value="Upravit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>

        @if (Model.RedirectedFrom != null)
        {
            if (Model.RedirectedFrom.Equals("Klient"))
            {
            <a asp-action="Details" asp-controller="@Model.RedirectedFrom" asp-route-id=@Model.KlientId>Zpět na klienta</a>
            }
            else
            {
                <a asp-action="Details" asp-controller="@Model.RedirectedFrom" asp-route-id=@Model.PojistnaUdalostId>Zpět na pojistnou událost</a>
            }
           <span>|</span> <a asp-action="Details" asp-route-id=@Model.ZavazekId>Přejdi k detailu závazku</a>
        }else{
           <a asp-action="Details" asp-route-id=@Model.ZavazekId>Zpět na detail</a>
        }
    
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Informacni_System_Pojistovny/Views/Zavazek/Index.cshtml
@model IEnumerable<Informacni_System_Pojistovny.Models.Entity.Zavazek>

@{
    ViewData["Title"] = "Závazky";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Závazky</h1>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Filtrovat dle řetězce: <input type="text" name="CurrentFilter" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Filtruj" class="btn btn-default" /> |
            <a asp-action="Index">Zrušit filtr</a>
        </p>
    </div>
</form>
@Html.Partial("_paging")
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vznik)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumSplatnosti)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vyse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatumSplaceni)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Popis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PojistnaUdalost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Vznik)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatumSplatnosti)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vyse)
                </td>
                <td>
                    @{
                        if (item.DatumSplaceni != null)
                        {
                            //Html.DisplayFor(modelItem => item.DatumSplaceni);  -- hmm, s dateTime? to hodně funguje...
                                                    <span>@(((DateTime)item.DatumSplaceni).ToString("dd.MM.yyyy"))</span>
                        }
                        else
                        {
                                      <span>Nesplaceno</span>
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Popis)
                </td>
                <td>
                    @Html.ActionLink("Přejít na pojistnou událost", "Details","PojistnaUdalost", new { id=item.PojistnaUdalost.PojistnaUdalostId })
                </td>
                <td>
                    @Html.ActionLink("Detail", "Details", new { id=item.ZavazekId })
                    @if (Context.User.IsInRole(UzivateleRole.Admin.ToString()) || Context.User.IsInRole(UzivateleRole.PriviledgedUser.ToString()))
                    {
                        <span> | @Html.ActionLink("Upravit", "Edit", new { id=item.ZavazekId }) |</span>
                        @Html.ActionLink("Smazat", "Delete", new { id=item.ZavazekId })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>